### ISSUE TITLE
非常感谢，请问一下，这个库如果用在生产环境，有什么需要注意的地方吗

### ISSUE THREAD

**Issue by playniuniu** [pseudocodes/go2ctp#2]
找了好几个 Golang 的 CTP 库，感觉这个库写的非常好， 非常感谢。

想请问一下，这个库现在的开发计划是怎样的？

如果在生产环境使用的话，还有什么需要注意的地方吗？

再次非常感谢作者

**Comment by pseudocodes** [comment]
目前该库封装基本稳定，相关类型定义会随 CTP 库更新而更新，已经实盘的用户目前还没报过 issue
计划今年内会开源基于该库的 trade-gateway 以及 trade-engine 实现
未来可能添加 ctp-mini 的封装，其他额外的封装功能可以看 pseudocodes/goctp 项目

**Comment by playniuniu** [comment]
好的，非常感谢，后续我也看看能否对  trade-gateway 和  trade-engine 有所贡献
