### ISSUE TITLE
v6.7.7 在 MacOS 下出问题

### ISSUE THREAD

**Issue by playniuniu** [pseudocodes/go2ctp#6]
MacOS, M2 芯片，使用 6.7.2 的 Lib，go.mod 使用 github.com/pseudocodes/go2ctp v0.0.0-20240709064520-c38cfcf846ed 没有任何问题，换成最新的6.7.7 的版本，go.mod 使用 github.com/pseudocodes/go2ctp v0.0.0-20240913143505-9acdadb3e0f7，编译的时候，提示 ld: framework 'thostmduserapi_se' not found，编译不过去

**Comment by pseudocodes** [comment]
修了一下 framework 库，你再试试最新提交

> MacOS, M2 芯片，使用 6.7.2 的 Lib，go.mod 使用 github.com/pseudocodes/go2ctp v0.0.0-20240709064520-c38cfcf846ed 没有任何问题，换成最新的6.7.7 的版本，go.mod 使用 github.com/pseudocodes/go2ctp v0.0.0-20240913143505-9acdadb3e0f7，编译的时候，提示 ld: framework 'thostmduserapi_se' not found，编译不过去

**Comment by playniuniu** [comment]
非常感谢，但是报了另外一个错误 mdapi_wrap.cxx:13:10: fatal error: 'iostream' file not found

**Comment by playniuniu** [comment]
好的，已经可以了，非常非常感谢。
