### ISSUE TITLE
MacOS 6.7.7 使用ctp_dyn连接openctp模拟环境的时候4097

### ISSUE THREAD

**Issue by tlsproxy** [pseudocodes/go2ctp#7]
大佬请问，MacOS 6.7.7 连接openctp模拟环境，版本使用ctp_dyn方式，ctp中的macos动态库连接的时候报错：CThostFtdcUserApiImplBase::OnSessionDisconnected[0x1007046f8][146145281][ 4097]

请问如何处理？

**Comment by tlsproxy** [comment]
同样版本连接CTP柜台正常

**Comment by pseudocodes** [comment]
自行去 openctp 官网下载正确版本的动态库
