### ISSUE TITLE
求一篇更详细一点的编译过程

### ISSUE THREAD

**Issue by beijibeijing** [pseudocodes/go2ctp#8]
大佬，ctp_dyn 使用需要用户明确提供动态库地址这种是非常方便，但是切换版本时怎么编译的还是不太明白啊，求一篇更详细一点编辑过程呗~

**Comment by pseudocodes** [comment]
> beijibeijing

稍微更新了下 Readme 文档和 Sample 中的代码
切换版本只用指明相关版本动态库的地址即可

**Comment by beijibeijing** [comment]
感谢 ！但是还是有点困惑。比如我切换成低版本的库，sample/simple_market/main.go中
`CTPLibPathLinux = "../../ctp/lib/v6.7.7_20240607_api_traderapi_se_linux64/thostmduserapi_se.so"`
我只需把这个路径下的thostmduserapi_se.so换成低版的就行了么？
ctp_dyn/目录下的这些文件不是用对应版本重新编译生成的么？主要这步骤有点困惑。

**Comment by pseudocodes** [comment]
> 感谢 ！但是还是有点困惑。比如我切换成低版本的库，sample/simple_market/main.go中 `CTPLibPathLinux = "../../ctp/lib/v6.7.7_20240607_api_traderapi_se_linux64/thostmduserapi_se.so"` 我只需把这个路径下的thostmduserapi_se.so换成低版的就行了么？ ctp_dyn/目录下的这些文件不是用对应版本重新编译生成的么？主要这步骤有点困惑。

现在还没找到比较适合 go 的编译期生成代码的方法，都是采用预先绑定版本生成的封装代码，降低版本的动态库加载后理论上只要编译符号不变一般不会出啥问题，具体还得你自己在生产环境上测试

**Comment by pseudocodes** [comment]
> 感谢 ！但是还是有点困惑。比如我切换成低版本的库，sample/simple_market/main.go中 `CTPLibPathLinux = "../../ctp/lib/v6.7.7_20240607_api_traderapi_se_linux64/thostmduserapi_se.so"` 我只需把这个路径下的thostmduserapi_se.so换成低版的就行了么？ ctp_dyn/目录下的这些文件不是用对应版本重新编译生成的么？主要这步骤有点困惑。

不同版本分支的封装代码只能加载对应版本的动态库 so/dylib， 版本不对会导致编译出来的程序运行时卡住或者报错
